Sprint2Mvc/Models/AddCollege.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Sprint2Mvc.Models
{
    public class AddCollege
    {
        [Required]
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }
    }
}

Sprint2Mvc/Models/AddCourse.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Sprint2Mvc.Models
{
    public class AddCourse
    {
        [Required]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }

        [Required]
        public int Duration { get; set; }

        public string Description { get; set; }
    }
}

Sprint2Mvc/Models/AddEnrollment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Sprint2Mvc.Models
{
    public class AddEnrollment
    {
        [Required]
        public int Id { get; set; }
        [Required]
        public int StudentId { get; set; }

        [Required]
        public int CourseId { get; set; }

        [Required]
        public DateTime CreatedDate { get; set; }




    }
}

Sprint2Mvc/Models/AddStudent.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Sprint2Mvc.Models
{
    public class AddStudent
    {
        [Required]
        public string Name { get; set; }

        [Required]
        public int StudentId { get; set;}

        public int ContactNo { get; set; }

        [Required]
        public int CollegeId { get; set; }

        public DateTime date { get; set; }
    }
}

Sprint2Mvc/Models/DisplayAllCourses.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Sprint2Mvc.Models
{
    public class DisplayAllCourses
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public int Duration { get; set; }

        public string Description { get; set; }
    }
}

Sprint2Mvc/Models/DisplayAllEnrollments.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Sprint2Mvc.Models
{
    public class DisplayAllEnrollments
    {
        public int Id { get; set; }

        public int CourseId { get; set; }

        public int StudentId { get; set; }

        public DateTime CreatedDate { get; set; }
    }
}

Sprint2Mvc/Models/DisplayStudentDetails.cs
using System;
using System.Collections.Generic;

using System.Linq;
using System.Web;

namespace Sprint2Mvc.Models
{
    public class DisplayStudentDetails
    {
        
        public int StudentId { get; set; }

        
        public string StudentName { get; set;}

       
        public int ContactNo { get; set; }
      
        public int CollegeId { get; set; }

        public DateTime CreatedDate { get; set; }
    }
}

Sprint2Mvc/Models/Login.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sprint2Mvc.Models
{
    public class Login
    {
        [Required]
        public string UserName { get; set; }

        [Required]
        public string Password { get; set; }

        [Required]
        [Display(Name ="Select Role")]
        public List<SelectListItem> Roles { get; set; }

        
    }
   
}

Sprint2Mvc/Models/UpdateCollege.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Sprint2Mvc.Models
{
    public class UpdateCollege
    {
       
            [Required]
            public int Id { get; set; }

            [Required]
            public string Name { get; set; }
        
    }
}

Sprint2Mvc/Models/UpdateCourse.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Sprint2Mvc.Models
{
    public class UpdateCourse
    {
        [Required]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }

        [Required]
        public int Duration {get; set; }

        public string Description { get; set; }
    }
}

Sprint2Mvc/Models/UpdateEnrollment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Sprint2Mvc.Models
{
    public class UpdateEnrollment
    {
        [Required]
        public int Id { get; set; }
        [Required]
        public int StudentId { get; set; }

        [Required]
        public int CourseId { get; set; }

        [Required]
        public DateTime CreatedDate { get; set; }

    }
}

Sprint2Mvc/Models/UpdateStudent.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Sprint2Mvc.Models
{
    public class UpdateStudent
    {
        [Required]
        public string Name { get; set; }

        [Required]
        public int StudentId { get; set; }

        public int ContactNo { get; set; }

        [Required]
        public int CollegeId { get; set; }

        public DateTime date { get; set; }
    }
}

Sprint2Mvc/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sprint2Mvc.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult AddStudent()
        {
            return View();
        }

        public ActionResult UpdateStudent()
        {
            return View();
        }

        public ActionResult AddEnrollment()
        {
            return View();
        }

        public ActionResult AddCollege()
        {
            return View();
        }

        public ActionResult UpdateCollege()
        {
            return View();
        }

        public ActionResult UpdateEnrollment()
        {
            return View();
        }

        public ActionResult UpdateCourse()
        {
            return View();
        }

        public ActionResult AddCourse()
        {
            return View();
        }
        public ActionResult DisplayStudentDetails_Faculty()
        {
            return View();
        }
        public ActionResult FacultyMainPage()
        {
            return View();
        }
    }
}

Sprint2Mvc/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sprint2Mvc.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }
    }
}

Sprint2Mvc/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sprint2Mvc.Controllers
{
    public class StudentController : Controller
    {
        // GET: Student
        public ActionResult UpdateStudent()
        {
            return View();
        }

        public ActionResult DisplayStudentDetails()
        {
            return View();
        }

        public ActionResult DisplayAllCourses()
        {
            return View();
        }

        public ActionResult DisplayAllEnrollment()
        {
            return View();
        }

        public ActionResult StudentMainPage()
        {
            return View();
        }
    }
}

Sprint2Mvc/Views/Admin/AddCollege.cshtml
@model Sprint2Mvc.Models.AddCollege

@{
    ViewBag.Title = "AddCollege";
}

<h1>ADD COLLEGE</h1>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">

        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">

        @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="ADD COLLEGE" class="btn btn-default" />
        </div>
    </div>
</div>
}



<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Sprint2Mvc/Views/Admin/AddCollge.cshtml
@model Sprint2Mvc.Models.AddCollege

@{
    ViewBag.Title = "AddCollge";
}

<h1>ADD COLLEGE</h1>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
       
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ADD COLLEGE" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Sprint2Mvc/Views/Admin/AddCourse.cshtml
@model Sprint2Mvc.Models.AddCourse

@{
    ViewBag.Title = "AddCourse";
}

<h1>ADD COURSE</h1>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
      
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Duration, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ADD" class="btn btn-default" />
            </div>
        </div>
    </div>
}



<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Sprint2Mvc/Views/Admin/AddEnrollment.cshtml
@model Sprint2Mvc.Models.AddEnrollment

@{
    ViewBag.Title = "AddEnrollment";
}

<h1>ADD ENROLLMENT</h1>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
       
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.StudentId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudentId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StudentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CourseId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CourseId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ADD" class="btn btn-default" />
            </div>
        </div>
    </div>
}



<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Sprint2Mvc/Views/Admin/AddStudent.cshtml
@model Sprint2Mvc.Models.AddStudent

@{
    ViewBag.Title = "AddStudent";
}

<h1>ADD STUDENT</h1>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
      
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StudentId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudentId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StudentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContactNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CollegeId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CollegeId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CollegeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ADD" class="btn btn-default" />
            </div>
        </div>
    </div>
}



<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Sprint2Mvc/Views/Admin/DisplayStudentDetails_Faculty.cshtml
@model Sprint2Mvc.Models.DisplayStudentDetails

@{
    ViewBag.Title = "DisplayStudentDetails_Faculty";
}

<h1>STUDENT DETAILS</h1>

<div>
    <label>FILTER BY :</label>
    <select class="form-control" name="FILTER BY">
        <optgroup>Select</optgroup>
        <option>Student Id</option>
        <option>College Id</option>
    </select>
    <br />
    <br />
    <button name="submit">SUBMIT</button>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StudentId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StudentId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StudentName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StudentName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CollegeId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CollegeId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

    </dl>
</div>
<p>
   
    @Html.ActionLink("Back to List", "Index")
</p>

Sprint2Mvc/Views/Admin/FacultyMainPage.cshtml
@{
    ViewBag.Title = "FacultyMainPage";
}

<h2>WELCOME !!! GREETINGS </h2>

<div style="background-color:aqua">
    <button type="submit" value="add_student" >ADD STUDENT</button>
    <br />
    <button type="submit" value="display_studentlists">DISPLAY STUDENTS LISTS</button>
    <br />
    <button type="submit" value="add_course">ADD COURSE</button>
    <br />
    <button type="submit" value="update_course">UPDATE COURSE</button>
    <br />

    <button type="submit" value="update_collegedetails">UPDATE COLLEGE DETAILS</button>
    <br />
    <button type="submit" value="display_enrollmentslists">DISPLAY ENROLLMENT LISTS</button>
    <br />
    <button type="submit" value="display_collegelists">DISPLAY COLLEGE LISTS</button>
    <br />
    <button type="submit" value="add_collegedetails">ADD COLLEGE DETAILS</button>
    <br />
    <button type="submit" value="add_enrollments">ADD ENROLLMENTS</button>
    <br />
    <button type="submit" value="update_enrollments">UPDATE ENROLLMENTS</button>









</div>
<br />
@Html.ActionLink("LOGOUT", "Index", "Login", null, new { @class = "btn btn-primary" })

Sprint2Mvc/Views/Admin/UpdateCollege.cshtml
@model Sprint2Mvc.Models.UpdateCollege

@{
    ViewBag.Title = "UpdateCollege";
}

<h1>UPDATE COLLEGE</h1>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    
    <hr />


    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
        </div>
    </div>
    <br />
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="UPDATE" class="btn btn-default" />
        </div>
    </div>
</div>
}



<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Sprint2Mvc/Views/Student/DisplayAllCourses.cshtml
@model Sprint2Mvc.Models.DisplayAllCourses

@{
    ViewBag.Title = "DisplayAllCourses";
}

<h2>ALL COURSES</h2>

<div>
    
    <hr />
    <dl class="dl-horizontal">
     
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Duration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Duration)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>

    @Html.ActionLink("Back ", "StudentMainPage", "Student", null,new{ @class = "btn btn-primary" })
</p>

Sprint2Mvc/Views/Student/DisplayAllEnrollment.cshtml
@model Sprint2Mvc.Models.DisplayAllEnrollments

@{
    ViewBag.Title = "DisplayAllEnrollment";
}

<h1>ALL ENROLLMENTS</h1>

<div>
  
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CourseId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CourseId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StudentId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StudentId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

    </dl>
</div>
<p>
    
    @Html.ActionLink("Back ", "StudentMainPage", "Student", null,new{ @class = "btn btn-primary" })
</p>

Sprint2Mvc/Views/Student/DisplayStudentDetails.cshtml
@model Sprint2Mvc.Models.DisplayStudentDetails

@{
    ViewBag.Title = "DisplayStudentDetails";
}

<h1> STUDENT DETAILS</h1>

<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StudentId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StudentId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StudentName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StudentName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CollegeId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CollegeId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

    </dl>
</div>
<p>

    @Html.ActionLink("Back ", "StudentMainPage", "Student", null,new{ @class = "btn btn-primary" })
</p>

Sprint2Mvc/Views/Student/StudentMainPage.cshtml
@{
    ViewBag.Title = "StudentMainPage";
}

<h1>WELCOME STUDENT!!!!!</h1>

<div style="background-color:aqua">
    <button type="submit" value="update_studentlists" s>UPDATE STUDENT LISTS</button>
    <br />
    <br />
    <button type="submit" value="display_studentlists">DISPLAY STUDENTS LISTS</button>
    <br />
    <br />
    <button type="submit" value="display_enrollmentslists">DISPLAY ENROLLMENTS LISTS</button>
    <br />
    <br />
    <button type="submit" value="display_courselists">DISPLAY COURSE LISTS</button>
    <br />
    <br />  







</div>
<br />
@Html.ActionLink("LOGOUT", "Index", "Login", null, new { @class = "btn btn-primary" })

Sprint2Mvc/Views/Student/UpdateStudent.cshtml
@model Sprint2Mvc.Models.UpdateStudent

@{
    ViewBag.Title = "UpdateStudent";
}

<h1>UPDATE STUDENT</h1>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
       
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StudentId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudentId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StudentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContactNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CollegeId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CollegeId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CollegeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.date, "", new { @class = "text-danger" })
            </div>
        </div>

        <br />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="UPDATE" class="btn btn-default" />
                @Html.ActionLink("Back ", "StudentMainPage", "Student", null,new{ @class = "btn btn-primary" })
            </div>
        </div>
    </div>
}



<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>